### ISSUE TITLE
add custom post type to a custom taxonomy with .save

### ISSUE THREAD

**Issue by vimes1984** [jeffsebring/angular-wp-api#11]
OK exactly this issue.. http://stackoverflow.com/questions/24833940/wp-api-custom-post-type-with-custom-taxonomy
I've solved this once but my given solution now fails me.. 
Please send me in the right direction, anyone help....

**Comment by jeffsebring** [comment]
I hope you found a solution. I have apparently been neglecting my Githubs.

Please let me know if there is functionality that WP-API supports, but this plugin does not.

**Comment by vimes1984** [comment]
Hello Jeff! 
I have no clue how I fixed this again... 
I think I customized the wp-api core to accept ""post_meta": $scope.dataform," where dataform is a object of key: value... 
If I managed to dig up what i did to extend this I'll fork and put up in a pull request.
